### ISSUE TITLE
Tests: Shippable -> Travis

### ISSUE THREAD

**Issue by pwalsh** [opentrials/tracker-ebola#36]
@zhenyab 

see there is a shippable config. We need to:

- [x] change it to travis
- [x] integrate code coverage with coveralls
- [x] ensure it runs green

**Comment by pwalsh** [comment]
@zhenyab you should start with this. I've enabled Travis and Coveralls

**Comment by zhenyab** [comment]
Should travis after successful tests deploy the master branch?

**Comment by pwalsh** [comment]
yes.

**Comment by zhenyab** [comment]
Fixed
