### ISSUE TITLE
chart not found on android?

### ISSUE THREAD

**Issue by pwalsh** [opentrials/tracker-ebola#65]
Can *anyone* reproduce this @benmeg @emmabeer @vitorbaptista @roll @nightsh @zhenyab  ?

![screenshot_2016-09-05-15-15-56](https://cloud.githubusercontent.com/assets/791678/18251167/2a24424c-7390-11e6-9248-a3ab1aaa020e.png)

**Comment by zhenyab** [comment]
This page appear in case if the url not mentioned in routes. What the URL?

**Comment by roll** [comment]
![screenshot_20160905-183641](https://cloud.githubusercontent.com/assets/557395/18252631/095b728a-7398-11e6-83bd-e9b410efacc6.png)

**Comment by pwalsh** [comment]
Can't reproduce.
